name: DataEmitter CI
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm audit --production
    - run: npm run build
    - run: npm run test
    - name: qube scan
      run: npm run sonarscan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONARQUBE_KEY: ${{ secrets.SONARQUBE_KEY }}
    - run: npm run doc
  echo_github_conds:
    runs-on: ubuntu-latest
    steps:
    - run: echo "ref = ${{github.ref}}, github.event = ${{ toJson(github.event) }}"
  publish:
    needs: build
    if: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: 'git config user.email "git@curium.rocks"'
    - run: 'git config user.name "ci"'
    - if: github.ref == 'refs/heads/development'
      run: npm version prerelease --preid-alpha
    - if: github.ref == 'refs/heads/master'
      run: npm version minor
    - if: github.ref == 'refs/head/development'
      run: git push origin HEAD:development
    - if: github.ref == 'refs/head/master'
      run: git push origin HEAD:master
    - run: npm config set //registry.npmjs.org/:_authToken ${NODE_ACCESS_TOKEN}
      env:
        NODE_ACCESS_TOKEN: ${{ secrets.NODE_ACCESS_TOKEN }}
    - run: npm publish --access public --dry-run