name: DataEmitter CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm audit --production
    - run: npm run build
    - run: npm test
    - name: sonarscan
      run: npm run sonarscan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONARQUBE_KEY: ${{ secrets.SONARQUBE_KEY }}
    - run: npm run doc